name: fade_scroll_app_bar
description: You can create a large appbar and make a smooth fade effect by swiping.
version: 0.0.6
homepage: https://github.com/sametcilingir/fadescrollappbar

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

